# AWS 서울 리전 Dashboard 연동 미지원
# org: qilip
# app: lara

service: lara-scraper

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  dev: devlopment
  prod: production

provider:
  name: aws
  deploymentMethod: direct
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  runtime: nodejs16.x
  memorySize: 1024
  timeout: 10
  logRetentionInDays: 14

functions:
  scraper:
    handler: src/handler.handler
    environment:
      NODE_ENV: ${self:custom.${opt:stage, 'dev'}}
